### Rota raiz
GET http://localhost:3333/

### Get Playlists
GET http://localhost:3333/playlist

### Get Playlist
GET http://localhost:3333/playlist/08a271e0-75c0-49ea-873b-7e3a4e0329dd

### Get Playlist
GET http://localhost:3333/playlist/'Rain'

### Create Playlist
POST http://localhost:3333/playlist
Content-Type: application/json

{
    "name": "Olha Yuri",
    "author": "God",
    "description": "SLEEP TOKEN"
}

### Update Playlist
PUT http://localhost:3333/playlist/c6dfb547-099f-4cb7-a156-9fad7ee2e087
Content-Type: application/json

{
    "name": "jsk",
    "author": "God",
    "description": "SLEEP TOKEN"
}

### Delete Playlist
DELETE http://localhost:3333/playlist/c3acb81b-453d-403b-b703-567a091a6ab4